// GENERATED CODE - DO NOT MODIFY BY HAND
import 'models.dart';

final Map<String, RoutineModel> seedRoutines = {
  'push-a': RoutineModel(
    id: 'push-a',
    name: 'Push A',
    type: 'push',
    day: 'Monday',
    subtitle: 'Chest · Shoulders · Triceps · Strength',
    exercises: [
      RoutineExerciseModel(
        name: 'Barbell Bench Press',
        sets: 5,
        reps: '3–5',
        restSeconds: 210,
        tip: 'Touch chest, controlled descent, elbows 45–75°.',
        badge: 'Compound',
        setup: ['Lie flat on bench, eyes under bar', 'Feet planted firmly on the floor', 'Grip slightly wider than shoulder-width', 'Squeeze shoulder blades together and down'],
        execution: ['Unrack and hold bar directly over shoulders', 'Lower bar to mid-chest with control', 'Elbows tucked at ~45 degree angle', 'Press bar back up to starting position'],
        mistakes: ['✓ Chest and triceps doing the work', '✗ Don\'t let elbows flare out to 90 degrees', '✗ Don\'t bounce bar off chest', '✗ Don\'t lift glutes off the bench'],
      ),
      RoutineExerciseModel(
        name: 'Overhead Press (Barbell)',
        sets: 4,
        reps: '4–6',
        restSeconds: 180,
        tip: 'Core braced, slight lean back at lockout, bar path straight up.',
        badge: 'Compound',
        setup: ['Stand with feet shoulder-width apart', 'Grip bar just outside shoulders', 'Bar rests on upper chest/clavicle', 'Brace core and squeeze glutes'],
        execution: ['Press bar straight up over head', 'Tuck chin slightly to let bar pass', 'Lock out elbows at the top', 'Lower under control to upper chest'],
        mistakes: ['✓ Shoulders and triceps engaged', '✗ Don\'t lean back excessively', '✗ Don\'t press forward, press straight up', '✗ Don\'t use leg drive'],
      ),
      RoutineExerciseModel(
        name: 'Incline DB Press',
        sets: 3,
        reps: '8–10',
        restSeconds: 120,
        tip: '30–45°, full stretch at bottom, squeeze at top.',
        badge: 'Compound',
        setup: ['Plant feet firmly', 'Brace core and stabilize shoulders'],
        execution: ['Press weight smoothly', 'Lock out or nearly lock out at the end', 'Lower under control'],
        mistakes: ['✓ Target muscles working', '✗ Don\'t flare elbows excessively', '✗ Don\'t lose tension at bottom'],
      ),
      RoutineExerciseModel(
        name: 'Cable Lateral Raise',
        sets: 4,
        reps: '12–15',
        restSeconds: 90,
        tip: 'Cross-body cable — constant tension unlike dumbbells.',
        badge: 'Isolation',
        setup: ['Stand, dumbbells at sides, palms inward', 'Slight forward lean (10–15°) — hits side delt more', 'Soft bend in elbows', 'Go lighter than you think you need'],
        execution: ['Raise arms out to sides — like pouring water', 'Lead with elbows, not hands', 'Stop when arms are parallel to floor (90°)', 'Lower slowly over 3 seconds', 'Don\'t rest at the bottom'],
        mistakes: ['✓ Burning on outer/top of shoulder', '✗ Don\'t shrug traps up', '✗ Don\'t swing or use momentum', '✗ Don\'t raise above parallel'],
      ),
      RoutineExerciseModel(
        name: 'Tricep Pushdown (Rope)',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Flare rope at bottom, full extension, hard squeeze.',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Elbows tucked and stationary'],
        execution: ['Extend arms fully', 'Squeeze at the contraction', 'Return to start with control'],
        mistakes: ['✓ Triceps/Quads working', '✗ Don\'t use momentum', '✗ Don\'t move elbows/knees'],
      ),
      RoutineExerciseModel(
        name: 'Overhead Tricep Extension (EZ-bar)',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Elbows tucked, full stretch overhead, full ROM.',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Elbows tucked and stationary'],
        execution: ['Extend arms fully', 'Squeeze at the contraction', 'Return to start with control'],
        mistakes: ['✓ Triceps/Quads working', '✗ Don\'t use momentum', '✗ Don\'t move elbows/knees'],
      ),
    ],
  ),
  'pull-a': RoutineModel(
    id: 'pull-a',
    name: 'Pull A',
    type: 'pull',
    day: 'Tuesday',
    subtitle: 'Back · Biceps · Strength',
    exercises: [
      RoutineExerciseModel(
        name: 'Weighted Pull-Up',
        sets: 4,
        reps: '4–6',
        restSeconds: 210,
        tip: 'Full dead hang, chin clears bar. Add weight via belt progressively.',
        badge: 'Compound',
        setup: ['Overhand grip, hands slightly wider than shoulders', 'Start from a dead hang — arms fully extended', 'Pull shoulder blades down and back first', 'Slight forward lean at the bottom'],
        execution: ['Think "pull elbows to hips" not "pull hands up"', 'Drive chest up toward the bar', 'Chin clears the bar = one rep', 'Lower slowly (3s) to full dead hang'],
        mistakes: ['✓ Feel lats (sides of back) — not just arms', '✗ Don\'t kip or use momentum', '✗ Don\'t half-rep — full hang every time', '✗ Can\'t do one yet? Use lat pulldown first'],
      ),
      RoutineExerciseModel(
        name: 'Seated Cable Row',
        sets: 4,
        reps: '6–8',
        restSeconds: 150,
        tip: 'Don\'t rock — isolate the squeeze. Elbows back, chest up. This is your primary row.',
        badge: 'Compound',
        setup: ['Sit tall, feet on the platform', 'Slight forward lean to grab handle', 'Chest up, back flat before you pull', 'Use a V-handle or wide bar'],
        execution: ['Pull handle to your belly button', 'Lead with elbows — drive them back', 'Squeeze shoulder blades hard at the end', 'Return slowly, feel the stretch', 'Don\'t rock forward and back'],
        mistakes: ['✓ Squeeze between shoulder blades at end', '✗ Don\'t use body momentum to row', '✗ Don\'t shrug traps up', '✗ Don\'t let lower back round'],
      ),
      RoutineExerciseModel(
        name: 'Lat Pulldown (Wide Grip)',
        sets: 3,
        reps: '8–10',
        restSeconds: 120,
        tip: 'Slight lean back, pull to upper chest, full stretch at top.',
        badge: 'Compound',
        setup: ['Sit securely, feet flat', 'Grip firmly'],
        execution: ['Pull bar down to upper chest', 'Squeeze back muscles', 'Return to start slowly'],
        mistakes: ['✓ Lats engaged', '✗ Don\'t lean back excessively', '✗ Don\'t use momentum'],
      ),
      RoutineExerciseModel(
        name: 'Bicep Curl Machine',
        sets: 4,
        reps: '8–10',
        restSeconds: 90,
        tip: 'Full ROM, slow 3s negative. Keep upper arms fixed on the pad — don\'t let elbows lift.',
        badge: 'Isolation',
        setup: ['Adjust seat so upper arms rest flat on pad', 'Elbows aligned with the machine\'s pivot point', 'Grip the handles — palms facing up', 'Sit tall, no slouching'],
        execution: ['Curl all the way up — full contraction', 'Squeeze hard for 1 second at the top', 'Lower slowly over 3 full seconds', 'Arms fully extended at the bottom — full stretch', 'No momentum — the pad locks you in'],
        mistakes: ['✓ Bicep burning — full squeeze at top', '✗ Don\'t let elbows lift off the pad', '✗ Don\'t rush the negative — 3s down always', '✗ Don\'t use a weight you can\'t fully control'],
      ),
      RoutineExerciseModel(
        name: 'Hammer Curl (DB)',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Neutral grip, no swinging — targets brachialis (underneath bicep).',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Grip firmly, elbows tucked at sides'],
        execution: ['Curl weight up smoothly', 'Squeeze at the top contraction', 'Lower weight under control'],
        mistakes: ['✓ Biceps working', '✗ Don\'t use momentum or swing', '✗ Don\'t move elbows forward'],
      ),
      RoutineExerciseModel(
        name: 'Face Pull (Cable)',
        sets: 3,
        reps: '15–20',
        restSeconds: 60,
        tip: 'Rope to forehead, external rotation. Light weight only.',
        badge: 'Accessory',
        setup: ['Cable at face height or above', 'Rope attachment, thumbs pointing toward you', 'Step back so cable is taut with arms extended', 'Light weight — this is a health exercise'],
        execution: ['Pull rope toward forehead, splitting it apart', 'Elbows flare out to sides at shoulder height', 'At the end: externally rotate — hands by ears', 'Hold 1 second, squeeze rear delts', 'Return slowly, repeat'],
        mistakes: ['✓ Back of shoulder (rear delt) squeezing', '✗ Don\'t pull to your chin — aim for forehead', '✗ Don\'t use heavy weight or momentum', '✗ Don\'t skip — protects shoulder health'],
      ),
    ],
  ),
  'legs-a': RoutineModel(
    id: 'legs-a',
    name: 'Legs A',
    type: 'legs',
    day: 'Wednesday',
    subtitle: 'Quads · Glutes · Calves · Squat Focus',
    exercises: [
      RoutineExerciseModel(
        name: 'Barbell Back Squat',
        sets: 5,
        reps: '3–5',
        restSeconds: 210,
        tip: 'Break parallel, brace core, knees track toes.',
        badge: 'Compound',
        setup: ['Bar on upper traps, grip to pull it in tight', 'Feet shoulder-width, toes out 15–30°', 'Big breath into belly, brace core hard', 'Unrack and take 2 steps back only'],
        execution: ['Push knees out toward toes', 'Descend like sitting back into a chair', 'Break parallel — hip crease below knee', 'Drive through the whole foot to stand', 'Keep chest up throughout'],
        mistakes: ['✓ Quads and glutes working equally', '✗ Don\'t let knees cave inward', '✗ Don\'t squat to just parallel — go below', '✗ Don\'t rise on your toes'],
      ),
      RoutineExerciseModel(
        name: 'Romanian Deadlift',
        sets: 3,
        reps: '8–10',
        restSeconds: 150,
        tip: 'Hinge — feel hamstrings load. No rounding. Bar drags down thighs.',
        badge: 'Compound',
        setup: ['Start standing, bar at hip level', 'Feet hip-width, soft bend in knees', 'Shoulder blades back and down', 'This is a hinge — move hips back'],
        execution: ['Push hips back — bar drags down thighs', 'Lower until you feel a deep hamstring stretch', 'Stop at your flexibility — don\'t force it', 'Drive hips forward to stand, squeeze glutes'],
        mistakes: ['✓ Deep stretch in back of thighs', '✗ Don\'t bend knees too much — becomes a squat', '✗ Don\'t round lower back to reach lower', '✗ Don\'t let bar drift away from legs'],
      ),
      RoutineExerciseModel(
        name: 'Leg Press',
        sets: 3,
        reps: '10–12',
        restSeconds: 120,
        tip: 'High, wide foot — glute emphasis. Full depth, don\'t lock out knees.',
        badge: 'Compound',
        setup: ['Plant feet firmly', 'Brace core and stabilize shoulders'],
        execution: ['Press weight smoothly', 'Lock out or nearly lock out at the end', 'Lower under control'],
        mistakes: ['✓ Target muscles working', '✗ Don\'t flare elbows excessively', '✗ Don\'t lose tension at bottom'],
      ),
      RoutineExerciseModel(
        name: 'Leg Extension',
        sets: 3,
        reps: '12–15',
        restSeconds: 90,
        tip: '3s negative, squeeze at top for 1 second.',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Elbows tucked and stationary'],
        execution: ['Extend arms fully', 'Squeeze at the contraction', 'Return to start with control'],
        mistakes: ['✓ Triceps/Quads working', '✗ Don\'t use momentum', '✗ Don\'t move elbows/knees'],
      ),
      RoutineExerciseModel(
        name: 'Standing Calf Raise',
        sets: 4,
        reps: '15–20',
        restSeconds: 60,
        tip: 'Full stretch at bottom, explosive up, 1s pause at top. See calf note below.',
        badge: 'Isolation',
        setup: ['Stand or sit tall', 'Slight bend in knees/elbows'],
        execution: ['Raise weight smoothly', 'Pause at the top', 'Lower under control'],
        mistakes: ['✓ Target muscles engaged', '✗ Don\'t swing the weight', '✗ Don\'t raise too high'],
      ),
      RoutineExerciseModel(
        name: 'Ab Wheel / Plank',
        sets: 3,
        reps: 'failure',
        restSeconds: 60,
        tip: '3 sets to failure or 45s plank. Keep lower back flat.',
        badge: 'Core',
        setup: ['Engage core, straight back', 'Hands/elbows under shoulders'],
        execution: ['Hold position or roll out smoothly', 'Maintain core tension', 'Return to start without sagging'],
        mistakes: ['✓ Core working', '✗ Don\'t let lower back sag', '✗ Don\'t hold breath'],
      ),
    ],
  ),
  'push-b': RoutineModel(
    id: 'push-b',
    name: 'Push B',
    type: 'push',
    day: 'Thursday',
    subtitle: 'Chest · Shoulders · Triceps · Volume',
    exercises: [
      RoutineExerciseModel(
        name: 'Incline Barbell Press',
        sets: 4,
        reps: '4–6',
        restSeconds: 180,
        tip: '30° only — steep incline shifts load to shoulders not upper chest.',
        badge: 'Compound',
        setup: ['Plant feet firmly', 'Brace core and stabilize shoulders'],
        execution: ['Press weight smoothly', 'Lock out or nearly lock out at the end', 'Lower under control'],
        mistakes: ['✓ Target muscles working', '✗ Don\'t flare elbows excessively', '✗ Don\'t lose tension at bottom'],
      ),
      RoutineExerciseModel(
        name: 'DB Shoulder Press',
        sets: 4,
        reps: '6–8',
        restSeconds: 120,
        tip: 'Greater ROM than barbell. Fixes shoulder imbalances.',
        badge: 'Compound',
        setup: ['Plant feet firmly', 'Brace core and stabilize shoulders'],
        execution: ['Press weight smoothly', 'Lock out or nearly lock out at the end', 'Lower under control'],
        mistakes: ['✓ Target muscles working', '✗ Don\'t flare elbows excessively', '✗ Don\'t lose tension at bottom'],
      ),
      RoutineExerciseModel(
        name: 'Pec Deck / Pec Fly Machine',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Feel the stretch at the widest point. Squeeze hard at the middle. Don\'t slam the weight.',
        badge: 'Isolation',
        setup: ['Adjust seat so handles are at chest height', 'Sit tall, back firmly against the pad', 'Grip handles, elbows slightly bent', 'Chest up, shoulders pulled back before starting'],
        execution: ['Bring handles together in a hugging arc', 'Squeeze chest hard when handles meet', 'Hold the squeeze for 1 full second', 'Open back slowly (3s) — feel the stretch', 'Don\'t slam the weight stack at the back'],
        mistakes: ['✓ Chest squeeze at centre, stretch at widest', '✗ Don\'t let shoulders roll forward', '✗ Don\'t use momentum — controlled always', '✗ Don\'t go so wide it stresses the shoulder'],
      ),
      RoutineExerciseModel(
        name: 'Seated Lateral Raise (DB)',
        sets: 4,
        reps: '12–15',
        restSeconds: 60,
        tip: 'Lean forward slightly. Lead with elbows, slow 3s negative.',
        badge: 'Isolation',
        setup: ['Stand or sit tall', 'Slight bend in knees/elbows'],
        execution: ['Raise weight smoothly', 'Pause at the top', 'Lower under control'],
        mistakes: ['✓ Target muscles engaged', '✗ Don\'t swing the weight', '✗ Don\'t raise too high'],
      ),
      RoutineExerciseModel(
        name: 'Weighted Dips',
        sets: 3,
        reps: '8–10',
        restSeconds: 120,
        tip: 'Slight forward lean for chest emphasis. Bodyweight first, then add load.',
        badge: 'Compound',
        setup: ['Plant feet firmly', 'Brace core and stabilize shoulders'],
        execution: ['Press weight smoothly', 'Lock out or nearly lock out at the end', 'Lower under control'],
        mistakes: ['✓ Target muscles working', '✗ Don\'t flare elbows excessively', '✗ Don\'t lose tension at bottom'],
      ),
      RoutineExerciseModel(
        name: 'Single-Arm Cable Pushdown',
        sets: 3,
        reps: '12 each',
        restSeconds: 60,
        tip: 'Full extension, wrist neutral, feel the lateral head fire.',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Elbows tucked and stationary'],
        execution: ['Extend arms fully', 'Squeeze at the contraction', 'Return to start with control'],
        mistakes: ['✓ Triceps/Quads working', '✗ Don\'t use momentum', '✗ Don\'t move elbows/knees'],
      ),
    ],
  ),
  'pull-b': RoutineModel(
    id: 'pull-b',
    name: 'Pull B',
    type: 'pull',
    day: 'Friday',
    subtitle: 'Back · Biceps · Deadlift + Volume',
    exercises: [
      RoutineExerciseModel(
        name: 'Conventional Deadlift',
        sets: 4,
        reps: '3–5',
        restSeconds: 210,
        tip: 'Bar over mid-foot, chest up, lat engagement before pull. See form guide.',
        badge: 'Compound',
        setup: ['Feet hip-width, bar over mid-foot', 'Hinge down, grip just outside legs', 'Shins vertical, hips above knees', 'Chest up, back flat — "proud chest"', 'Big breath, brace core maximally'],
        execution: ['"Push the floor away" — not "pull up"', 'Bar drags up your shins and thighs', 'Hips and shoulders rise at the same rate', 'Lock out: stand tall, squeeze glutes hard', 'Hinge back down — don\'t drop the bar'],
        mistakes: ['✓ Hamstrings and glutes loading, back tight', '✗ Don\'t round your lower back — ever', '✗ Don\'t let bar drift away from body', '✗ Don\'t jerk — build tension first, then pull'],
      ),
      RoutineExerciseModel(
        name: 'Chest-Supported DB Row',
        sets: 4,
        reps: '8–10',
        restSeconds: 120,
        tip: 'Lie chest on 45° bench — eliminates all body English. Pure back work.',
        badge: 'Compound',
        setup: ['Brace core, maintain straight back', 'Grip firmly'],
        execution: ['Pull weight toward torso', 'Squeeze shoulder blades together', 'Lower with control'],
        mistakes: ['✓ Back muscles engaged', '✗ Don\'t jerk the weight', '✗ Don\'t round lower back'],
      ),
      RoutineExerciseModel(
        name: 'Wide-Grip Lat Pulldown',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Slight lean back, pull to upper chest, full stretch at top.',
        badge: 'Compound',
        setup: ['Sit securely, feet flat', 'Grip firmly'],
        execution: ['Pull bar down to upper chest', 'Squeeze back muscles', 'Return to start slowly'],
        mistakes: ['✓ Lats engaged', '✗ Don\'t lean back excessively', '✗ Don\'t use momentum'],
      ),
      RoutineExerciseModel(
        name: 'Bicep Curl Machine',
        sets: 4,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Full ROM, 3s negative. Upper arms fixed on pad at all times.',
        badge: 'Isolation',
        setup: ['Adjust seat so upper arms rest flat on pad', 'Elbows aligned with the machine\'s pivot point', 'Grip the handles — palms facing up', 'Sit tall, no slouching'],
        execution: ['Curl all the way up — full contraction', 'Squeeze hard for 1 second at the top', 'Lower slowly over 3 full seconds', 'Arms fully extended at the bottom — full stretch', 'No momentum — the pad locks you in'],
        mistakes: ['✓ Bicep burning — full squeeze at top', '✗ Don\'t let elbows lift off the pad', '✗ Don\'t rush the negative — 3s down always', '✗ Don\'t use a weight you can\'t fully control'],
      ),
      RoutineExerciseModel(
        name: 'Incline DB Curl',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Lie on 45° bench — maximum bicep stretch at bottom.',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Grip firmly, elbows tucked at sides'],
        execution: ['Curl weight up smoothly', 'Squeeze at the top contraction', 'Lower weight under control'],
        mistakes: ['✓ Biceps working', '✗ Don\'t use momentum or swing', '✗ Don\'t move elbows forward'],
      ),
      RoutineExerciseModel(
        name: 'Rear Delt Fly (Machine)',
        sets: 3,
        reps: '15',
        restSeconds: 60,
        tip: 'Elbows slightly bent, lead wide. Prevents internal rotation.',
        badge: 'Isolation',
        setup: ['Set up securely and brace core', 'Use an appropriate weight'],
        execution: ['Perform movement smoothly', 'Focus on muscle contraction', 'Control the negative'],
        mistakes: ['✓ Target muscle engaged', '✗ Don\'t use momentum', '✗ Don\'t rush the reps'],
      ),
    ],
  ),
  'legs-b': RoutineModel(
    id: 'legs-b',
    name: 'Legs B',
    type: 'legs',
    day: 'Saturday',
    subtitle: 'Glutes · Hamstrings · Posterior Chain',
    exercises: [
      RoutineExerciseModel(
        name: 'Sumo Deadlift',
        sets: 4,
        reps: '5–6',
        restSeconds: 180,
        tip: 'Wide stance, toes out ~45°, grip inside legs. Torso more upright than conventional. Drives through heels and squeeze glutes hard at lockout.',
        badge: 'Compound',
        setup: ['Wide stance — feet near the plates', 'Toes pointed out ~45°', 'Grip the bar inside your legs, narrow grip', 'Hips lower than conventional — more squat-like', 'Chest up, shins nearly vertical'],
        execution: ['Push knees out hard as you pull', 'Drive through heels, not toes', 'Bar stays close to body — drags up inner thighs', 'Lock out by squeezing glutes — stand tall', 'Lower with control, reset each rep'],
        mistakes: ['✓ Glutes and inner thighs doing the work', '✗ Don\'t let knees cave in — push them out', '✗ Don\'t round lower back', '✗ Don\'t let hips shoot up at the start'],
      ),
      RoutineExerciseModel(
        name: 'Bulgarian Split Squat (DB)',
        sets: 4,
        reps: '8 each',
        restSeconds: 120,
        tip: 'Rear foot elevated, lean forward slightly for glute emphasis. Start bodyweight-only for 2 weeks.',
        badge: 'Compound',
        setup: ['Plant feet securely', 'Brace core'],
        execution: ['Move through full range of motion', 'Keep knees tracking over toes', 'Return to start'],
        mistakes: ['✓ Leg muscles working', '✗ Don\'t let knees cave in', '✗ Don\'t lift heels'],
      ),
      RoutineExerciseModel(
        name: 'Seated Leg Curl',
        sets: 4,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Hip flexed = greater hamstring stretch. Slow 3s negative every rep.',
        badge: 'Isolation',
        setup: ['Stand tall or sit securely', 'Grip firmly, elbows tucked at sides'],
        execution: ['Curl weight up smoothly', 'Squeeze at the top contraction', 'Lower weight under control'],
        mistakes: ['✓ Biceps working', '✗ Don\'t use momentum or swing', '✗ Don\'t move elbows forward'],
      ),
      RoutineExerciseModel(
        name: 'Stiff-Leg Deadlift (DB)',
        sets: 3,
        reps: '10–12',
        restSeconds: 120,
        tip: 'More stretch than RDL, slight knee bend. Feel every inch of hamstring.',
        badge: 'Compound',
        setup: ['Plant feet securely', 'Brace core'],
        execution: ['Move through full range of motion', 'Keep knees tracking over toes', 'Return to start'],
        mistakes: ['✓ Leg muscles working', '✗ Don\'t let knees cave in', '✗ Don\'t lift heels'],
      ),
      RoutineExerciseModel(
        name: 'Seated Calf Raise',
        sets: 4,
        reps: '15–20',
        restSeconds: 60,
        tip: 'Full ROM, 3s down, 1s pause at stretch. Add weight week 3 onwards.',
        badge: 'Isolation',
        setup: ['Stand or sit tall', 'Slight bend in knees/elbows'],
        execution: ['Raise weight smoothly', 'Pause at the top', 'Lower under control'],
        mistakes: ['✓ Target muscles engaged', '✗ Don\'t swing the weight', '✗ Don\'t raise too high'],
      ),
    ],
  ),
};
