// GENERATED CODE - DO NOT MODIFY BY HAND
import 'models.dart';

final Map<String, RoutineModel> seedRoutines = {
  'push-a': RoutineModel(
    id: 'push-a',
    name: 'Push A',
    type: 'push',
    day: 'Monday',
    subtitle: 'Chest · Shoulders · Triceps — Strength',
    exercises: [
      RoutineExerciseModel(
        name: 'Barbell Bench Press',
        sets: 5,
        reps: '3–5',
        restSeconds: 210,
        tip: 'Arch slightly, retract scapula, touch chest every rep',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Overhead Press (Barbell)',
        sets: 4,
        reps: '4–6',
        restSeconds: 180,
        tip: 'Brace core, bar path slightly forward, full lock out',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Incline Dumbbell Press',
        sets: 3,
        reps: '8–10',
        restSeconds: 120,
        tip: '30–45° angle, full stretch at bottom',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Cable Lateral Raise',
        sets: 4,
        reps: '12–15',
        restSeconds: 90,
        tip: 'Cross-body cable, constant tension on side delts',
        badge: 'Isolation',
        setup: ['Stand, dumbbells at sides, palms inward', 'Slight forward lean (10–15°) — hits side delt more', 'Soft bend in elbows', 'Go lighter than you think you need'],
        execution: ['Raise arms out to sides — like pouring water', 'Lead with elbows, not hands', 'Stop when arms are parallel to floor (90°)', 'Lower slowly over 3 seconds', 'Don\'t rest at the bottom'],
        mistakes: ['✓ Burning on outer/top of shoulder', '✗ Don\'t shrug traps up', '✗ Don\'t swing or use momentum', '✗ Don\'t raise above parallel'],
      ),
      RoutineExerciseModel(
        name: 'Tricep Pushdown (Rope)',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Flare rope at bottom, hard squeeze',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Overhead Tricep Extension',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'EZ-bar, elbows tucked, full overhead ROM',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
    ],
  ),
  'pull-a': RoutineModel(
    id: 'pull-a',
    name: 'Pull A',
    type: 'pull',
    day: 'Tuesday',
    subtitle: 'Back · Biceps — Strength',
    exercises: [
      RoutineExerciseModel(
        name: 'Weighted Pull-Up',
        sets: 4,
        reps: '4–6',
        restSeconds: 210,
        tip: 'Full dead hang, chin clears bar — add weight progressively',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Barbell Bent-Over Row',
        sets: 4,
        reps: '4–6',
        restSeconds: 180,
        tip: 'Overhand grip, row to lower chest, retract scapula',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Seated Cable Row',
        sets: 3,
        reps: '8–10',
        restSeconds: 120,
        tip: 'Don\'t rock torso — isolate the back squeeze',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Straight-Arm Pulldown',
        sets: 3,
        reps: '12–15',
        restSeconds: 90,
        tip: 'Arms straight, feel lats stretching at top',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Barbell Curl',
        sets: 4,
        reps: '5–7',
        restSeconds: 120,
        tip: 'Strict — no swinging. Supinate fully at top',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Incline Dumbbell Curl',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: '45° bench — full bicep stretch at bottom',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Face Pull (Cable)',
        sets: 3,
        reps: '15–20',
        restSeconds: 60,
        tip: 'Rope to forehead, external rotation — shoulder health',
        badge: 'Accessory',
        setup: ['Cable at face height or above', 'Rope attachment, thumbs pointing toward you', 'Step back so cable is taut with arms extended', 'Light weight — this is a health exercise'],
        execution: ['Pull rope toward forehead, splitting it apart', 'Elbows flare out to sides at shoulder height', 'At the end: externally rotate — hands by ears', 'Hold 1 second, squeeze rear delts', 'Return slowly, repeat'],
        mistakes: ['✓ Back of shoulder (rear delt) squeezing', '✗ Don\'t pull to your chin — aim for forehead', '✗ Don\'t use heavy weight or momentum', '✗ Don\'t skip — protects shoulder health'],
      ),
    ],
  ),
  'legs-a': RoutineModel(
    id: 'legs-a',
    name: 'Legs A',
    type: 'legs',
    day: 'Wednesday',
    subtitle: 'Quad Dominant — Squat Focus',
    exercises: [
      RoutineExerciseModel(
        name: 'Barbell Back Squat',
        sets: 5,
        reps: '3–5',
        restSeconds: 210,
        tip: 'Break parallel, brace hard, knees track toes',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Romanian Deadlift',
        sets: 3,
        reps: '8–10',
        restSeconds: 180,
        tip: 'Hinge at hips, feel hamstring load, no rounding',
        badge: 'Compound',
        setup: ['Start standing, bar at hip level', 'Feet hip-width, soft bend in knees', 'Shoulder blades back and down', 'This is a hinge — move hips back'],
        execution: ['Push hips back — bar drags down thighs', 'Lower until you feel a deep hamstring stretch', 'Stop at your flexibility — don\'t force it', 'Drive hips forward to stand, squeeze glutes'],
        mistakes: ['✓ Deep stretch in back of thighs', '✗ Don\'t bend knees too much — becomes a squat', '✗ Don\'t round lower back to reach lower', '✗ Don\'t let bar drift away from legs'],
      ),
      RoutineExerciseModel(
        name: 'Leg Press',
        sets: 3,
        reps: '10–12',
        restSeconds: 120,
        tip: 'High foot placement for glutes, full depth',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Leg Extension',
        sets: 3,
        reps: '12–15',
        restSeconds: 90,
        tip: 'Slow 3s negative, squeeze hard at top',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Seated Calf Raise',
        sets: 4,
        reps: '12–15',
        restSeconds: 60,
        tip: 'Full stretch at bottom, 1s pause, explosive up',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Ab Wheel / Plank',
        sets: 3,
        reps: 'AMRAP',
        restSeconds: 60,
        tip: 'Core finisher — 45s hold or failure',
        badge: 'Accessory',
        setup: [],
        execution: [],
        mistakes: [],
      ),
    ],
  ),
  'push-b': RoutineModel(
    id: 'push-b',
    name: 'Push B',
    type: 'push',
    day: 'Thursday',
    subtitle: 'Chest · Shoulders · Triceps — Volume',
    exercises: [
      RoutineExerciseModel(
        name: 'Incline Barbell Press',
        sets: 4,
        reps: '4–6',
        restSeconds: 180,
        tip: '30° incline — upper chest focus',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Dumbbell Shoulder Press',
        sets: 4,
        reps: '6–8',
        restSeconds: 150,
        tip: 'Neutral grip, full ROM',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Flat Dumbbell Flye',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Wide arc, stretch pec at bottom',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Machine Chest Press',
        sets: 3,
        reps: '12–15',
        restSeconds: 90,
        tip: 'Burnout — controlled reps, squeeze chest',
        badge: 'Accessory',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Seated Lateral Raise',
        sets: 4,
        reps: '12–15',
        restSeconds: 60,
        tip: 'Lead with elbows not wrists',
        badge: 'Isolation',
        setup: ['Stand, dumbbells at sides, palms inward', 'Slight forward lean (10–15°) — hits side delt more', 'Soft bend in elbows', 'Go lighter than you think you need'],
        execution: ['Raise arms out to sides — like pouring water', 'Lead with elbows, not hands', 'Stop when arms are parallel to floor (90°)', 'Lower slowly over 3 seconds', 'Don\'t rest at the bottom'],
        mistakes: ['✓ Burning on outer/top of shoulder', '✗ Don\'t shrug traps up', '✗ Don\'t swing or use momentum', '✗ Don\'t raise above parallel'],
      ),
      RoutineExerciseModel(
        name: 'Weighted Dips',
        sets: 3,
        reps: '8–10',
        restSeconds: 120,
        tip: 'Forward lean for chest emphasis, full depth',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Single-Arm Cable Pushdown',
        sets: 3,
        reps: '12 each',
        restSeconds: 60,
        tip: 'Greater isolation than two-arm version',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
    ],
  ),
  'pull-b': RoutineModel(
    id: 'pull-b',
    name: 'Pull B',
    type: 'pull',
    day: 'Friday',
    subtitle: 'Back · Biceps — Volume & Thickness',
    exercises: [
      RoutineExerciseModel(
        name: 'Conventional Deadlift',
        sets: 4,
        reps: '3–5',
        restSeconds: 210,
        tip: 'Bar over mid-foot, lat engagement before pull',
        badge: 'Compound',
        setup: ['Feet hip-width, bar over mid-foot', 'Hinge down, grip just outside legs', 'Shins vertical, hips above knees', 'Chest up, back flat — "proud chest"', 'Big breath, brace core maximally'],
        execution: ['"Push the floor away" — not "pull up"', 'Bar drags up your shins and thighs', 'Hips and shoulders rise at the same rate', 'Lock out: stand tall, squeeze glutes hard', 'Hinge back down — don\'t drop the bar'],
        mistakes: ['✓ Hamstrings and glutes loading, back tight', '✗ Don\'t round your lower back — ever', '✗ Don\'t let bar drift away from body', '✗ Don\'t jerk — build tension first, then pull'],
      ),
      RoutineExerciseModel(
        name: 'Chest-Supported DB Row',
        sets: 4,
        reps: '8–10',
        restSeconds: 120,
        tip: 'Chest on incline bench — pure back work',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Wide-Grip Lat Pulldown',
        sets: 3,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Pull to upper chest, stretch fully at top',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Single-Arm DB Row',
        sets: 3,
        reps: '10 each',
        restSeconds: 90,
        tip: 'Elbow drives back — big ROM',
        badge: 'Accessory',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Hammer Curl',
        sets: 4,
        reps: '8–10',
        restSeconds: 90,
        tip: 'Neutral grip — brachialis for arm thickness',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Cable Curl (EZ-bar)',
        sets: 3,
        reps: '12–15',
        restSeconds: 60,
        tip: 'Constant tension, slow negative',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Rear Delt Fly',
        sets: 3,
        reps: '15',
        restSeconds: 60,
        tip: 'Elbows wide — shoulder balance',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
    ],
  ),
  'legs-b': RoutineModel(
    id: 'legs-b',
    name: 'Legs B',
    type: 'legs',
    day: 'Saturday',
    subtitle: 'Posterior Chain — Hamstrings & Glutes',
    exercises: [
      RoutineExerciseModel(
        name: 'Barbell Hip Thrust',
        sets: 4,
        reps: '6–8',
        restSeconds: 180,
        tip: 'Drive through heels, squeeze glutes at top',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Bulgarian Split Squat',
        sets: 4,
        reps: '8 each',
        restSeconds: 120,
        tip: 'Rear foot elevated, lean forward slightly',
        badge: 'Compound',
        setup: ['Rear foot elevated on bench, laces down', 'Front foot far enough that shin stays vertical', 'Start with hands on hips — learn balance first', 'Stand tall, core braced'],
        execution: ['Lower straight down — don\'t lunge forward', 'Front knee tracks over toes, not caving in', 'Rear knee drops toward floor', 'Drive through front heel to return', 'All reps one side, then switch'],
        mistakes: ['✓ Front quad and glute doing the work', '✗ Don\'t lean too far forward', '✗ Don\'t add weight until balance is solid', '✗ Bodyweight only for the first 2 weeks'],
      ),
      RoutineExerciseModel(
        name: 'Seated Leg Curl',
        sets: 4,
        reps: '10–12',
        restSeconds: 90,
        tip: 'Slow 3s negative — max hamstring stretch',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Stiff-Leg Deadlift (DB)',
        sets: 3,
        reps: '10–12',
        restSeconds: 120,
        tip: 'More stretch than RDL, slight knee bend',
        badge: 'Compound',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Cable Glute Kickback',
        sets: 3,
        reps: '15 each',
        restSeconds: 60,
        tip: 'Squeeze at top, controlled return',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
      RoutineExerciseModel(
        name: 'Standing Calf Raise',
        sets: 5,
        reps: '15',
        restSeconds: 60,
        tip: 'Full ROM, 3s negative — calves need volume',
        badge: 'Isolation',
        setup: [],
        execution: [],
        mistakes: [],
      ),
    ],
  ),
};
